import type { CompetitionConfig } from '../types';

export const COMPETITIONS: CompetitionConfig[] = [
  {
    id: 2021,
    code: 'PL',
    name: 'Premier League',
    shortName: 'PL',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    type: 'LEAGUE',
    color: '#3d195b',
    emblem: 'https://crests.football-data.org/PL.png',
  },
  {
    id: 2014,
    code: 'PD',
    name: 'La Liga',
    shortName: 'La Liga',
    country: 'Spain',
    flag: '🇪🇸',
    type: 'LEAGUE',
    color: '#ee8707',
    emblem: 'https://crests.football-data.org/PD.png',
  },
  {
    id: 2019,
    code: 'SA',
    name: 'Serie A',
    shortName: 'Serie A',
    country: 'Italy',
    flag: '🇮🇹',
    type: 'LEAGUE',
    color: '#024494',
    emblem: 'https://crests.football-data.org/SA.png',
  },
  {
    id: 2002,
    code: 'BL1',
    name: 'Bundesliga',
    shortName: 'Bundesliga',
    country: 'Germany',
    flag: '🇩🇪',
    type: 'LEAGUE',
    color: '#d20515',
    emblem: 'https://crests.football-data.org/BL1.png',
  },
  {
    id: 2015,
    code: 'FL1',
    name: 'Ligue 1',
    shortName: 'Ligue 1',
    country: 'France',
    flag: '🇫🇷',
    type: 'LEAGUE',
    color: '#1a3f7a',
    emblem: 'https://crests.football-data.org/FL1.png',
  },
  {
    id: 2001,
    code: 'CL',
    name: 'Champions League',
    shortName: 'UCL',
    country: 'Europe',
    flag: '🇪🇺',
    type: 'CUP',
    color: '#062b5b',
    emblem: 'https://crests.football-data.org/CL.png',
  },
  {
    id: 2137,
    code: 'FAC',
    name: 'FA Cup',
    shortName: 'FA Cup',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    type: 'CUP',
    color: '#c8102e',
    emblem: 'https://crests.football-data.org/FAC.png',
  },
  {
    id: 2079,
    code: 'DFB',
    name: 'DFB-Pokal',
    shortName: 'DFB-Pokal',
    country: 'Germany',
    flag: '🇩🇪',
    type: 'CUP',
    color: '#000000',
    emblem: 'https://crests.football-data.org/DFB.png',
  },
  {
    id: 2081,
    code: 'CDR',
    name: 'Copa del Rey',
    shortName: 'Copa del Rey',
    country: 'Spain',
    flag: '🇪🇸',
    type: 'CUP',
    color: '#aa151b',
    emblem: 'https://crests.football-data.org/CDR.png',
  },
  {
    id: 2080,
    code: 'CIT',
    name: 'Coppa Italia',
    shortName: 'Coppa Italia',
    country: 'Italy',
    flag: '🇮🇹',
    type: 'CUP',
    color: '#009246',
    emblem: 'https://crests.football-data.org/CIT.png',
  },
  {
    id: 2083,
    code: 'LFR',
    name: 'Coupe de France',
    shortName: 'Coupe de France',
    country: 'France',
    flag: '🇫🇷',
    type: 'CUP',
    color: '#002395',
    emblem: 'https://crests.football-data.org/LFR.png',
  },
];

export const LEAGUE_COMPETITIONS = COMPETITIONS.filter(c => c.type === 'LEAGUE');
export const CUP_COMPETITIONS = COMPETITIONS.filter(c => c.type === 'CUP');

export const getCompetitionByCode = (code: string) =>
  COMPETITIONS.find(c => c.code === code);

export const getCompetitionById = (id: number) =>
  COMPETITIONS.find(c => c.id === id);

export const POSITIONS: Record<string, string> = {
  Goalkeeper: 'GK',
  Defender: 'DEF',
  'Centre-Back': 'CB',
  'Left-Back': 'LB',
  'Right-Back': 'RB',
  Midfielder: 'MID',
  'Central Midfield': 'CM',
  'Defensive Midfield': 'CDM',
  'Attacking Midfield': 'CAM',
  'Left Midfield': 'LM',
  'Right Midfield': 'RM',
  Forward: 'FWD',
  'Centre-Forward': 'CF',
  'Left Winger': 'LW',
  'Right Winger': 'RW',
  Offence: 'FWD',
  Defence: 'DEF',
  Midfield: 'MID',
};

export const STAGE_LABELS: Record<string, string> = {
  REGULAR_SEASON: 'Matchday',
  SEMI_FINALS: 'Semi-Final',
  QUARTER_FINALS: 'Quarter-Final',
  ROUND_OF_16: 'Round of 16',
  ROUND_OF_32: 'Round of 32',
  GROUP_STAGE: 'Group Stage',
  FINAL: 'Final',
  THIRD_PLACE: '3rd Place',
  PLAY_OFF: 'Play-Off',
};
